services:
  queue:
    image: queue
    build: ./queue/
    restart: always
    ports:
      - "5000:5000"
      - "6379:6379"
  
  worker:
    image: python:3.10-alpine
    restart: always
    depends_on:
      - queue
    volumes:
      - ./worker/:/usr/src/app/:ro
    working_dir: /usr/src/app/
    command: sh -c 'pip install rq && rq worker --url redis://queue:6379/0'
  
  redisinsight:
    image: redislabs/redisinsight
    depends_on: [ queue ]
    ports: [ 3000:5000 ]
  
  rq-dashboard:
    image: eoranged/rq-dashboard:latest
    ports: [ 9181:9181 ]
    depends_on: [ queue ]
    restart: always
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://queue:6379
